version: "2"
services:
  redmine-3.2-mariadb:
    image: redmine:3.2
    ports:
      - "3011:3000"
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_DATABASE: redmine_32
    env_file:
      - env
    extra_hosts:
      - "mariadb:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  redmine-3.3-mariadb:
    image: redmine:3.3
    ports:
      - "3012:3000"
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_DATABASE: redmine_33
    env_file:
      - env
    extra_hosts:
      - "mariadb:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  redmine-3.4-mariadb:
    image: redmine:3.4
    ports:
      - "3013:3000"
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_DATABASE: redmine_34
    env_file:
      - env
    extra_hosts:
      - "mariadb:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  redmine-3.2-postgresql:
    image: redmine:3.2
    ports:
      - "3021:3000"
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_DATABASE: redmine-3.2
    env_file:
      - env
    extra_hosts:
      - "postgresql:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  redmine-3.3-postgresql:
    image: redmine:3.3
    ports:
      - "3022:3000"
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_DATABASE: redmine-3.3
    env_file:
      - env
    extra_hosts:
      - "postgresql:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  redmine-3.4-postgresql:
    image: redmine:3.4
    ports:
      - "3023:3000"
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_DATABASE: redmine-3.4
    env_file:
      - env
    extra_hosts:
      - "postgresql:172.17.0.1"
    volumes:
      - .:/usr/src/redmine/plugins/full_text_search:ro

  pgroonga:
    build:
      context: .
      dockerfile: dockerfiles/pgroonga/Dockerfile
    volumes:
      - postgresql_data:/var/lib/postgresql

  mroonga:
    build:
      context: .
      dockerfile: dockerfiles/mroonga/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgresql_data:
  mysql_data:

